### ISSUE TITLE
Escolha do site

### ISSUE THREAD

**Issue by LucasLopesFrazao** [Interacao-Humano-Computador/2023.1-DDS-UnB#4]
# Escolha do site

## Descrição
Cada membro deve escolher ao menos 1 site para levar para a reunião do dia 07/04 para a escolha do site ser feita.

## Tarefas

- [ ] Escolher um site que seja feio ou que tenha má usabilidade ou semelhantes

**Comment by LucasLopesFrazao** [comment]
Site do Fluminense - https://www.fluminense.com.br/site/
Manga Livre - https://mangalivre.net/
Crunchyroll - https://www.crunchyroll.com/pt-br/
Correios - https://www.correios.com.br/

**Comment by PedroHenrique2077** [comment]
Site do Detran-GO - https://www.detran.go.gov.br/psw/#/pages/pagina-inicial
Senado Federal - https://www12.senado.leg.br/hpsenado
Aliexpress - https://pt.aliexpress.com/?gatewayAdapt=glo2bra

**Comment by SamuelGSouza** [comment]
Central Expresso - https://www.centralexpresso.com/index.html
